const views = {
  RECOVER_PASSWORD_FORM_VIEW: 'RECOVER_PASSWORD_FORM_VIEW',
  RECOVER_PASSWORD_INSTRUCTIONS_VIEW: 'RECOVER_PASSWORD_INSTRUCTIONS_VIEW',
  RESET_PASSWORD_VIEW: 'RESET_PASSWORD_VIEW',
  RESET_PASSWORD_INSTRUCTIONS_VIEW: 'RESET_PASSWORD_INSTRUCTIONS_VIEW',
}

export default views;