const views = {
  REGISTER_STEP_1_VIEW: 'REGISTER_STEP_1_VIEW',
  REGISTER_STEP_2_VIEW: 'REGISTER_STEP_2_VIEW',
  REGISTER_INSTRUCTIONS_VIEW: 'REGISTER_INSTRUCTIONS_VIEW',
  REGISTER_CONFIRMATION_VIEW: 'REGISTER_CONFIRMATION_VIEW',
  REGISTER_CONFIRMATION_ERROR_VIEW: 'REGISTER_CONFIRMATION_ERROR_VIEW',
}

export default views;