export const dialogs = {
  ADD_ADDRESS_DIALOG: 'ADD_ADDRESS_DIALOG',
  ADDRESS_PICKER_DIALOG: 'ADDRESS_PICKER_DIALOG',
  ADD_CARD_DIALOG: 'ADD_CARD_DIALOG',
  CARD_PICKER_DIALOG: 'CARD_PICKER_DIALOG',
  PLACE_ORDER_CONFIRMATION: 'PLACE_ORDER_CONFIRMATION',
}

export const sections = {
  SHIPPING_ADDRESS_SECTION: 'SHIPPING_ADDRESS_SECTION',
  PAYMENT_METHOD_SECTION: 'PAYMENT_METHOD_SECTION',
}

const checkoutConstants = {
  dialogs,
  sections,
};

export default checkoutConstants;