const views = {
  LOGIN_FORM_VIEW: 'LOGIN_FORM_VIEW',
  CONFIRM_EMAIL_ERROR_VIEW: 'CONFIRM_EMAIL_ERROR_VIEW',
  CONFIRM_EMAIL_INTRUCTIONS_VIEW: 'RECOVER_PASSWORD_INSTRUCTIONS_VIEW',
}

export default views;