// sessionActions

export const LOGIN_FETCH = 'LOGIN_FETCH';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_CONFIRMATION_ERROR = 'LOGIN_CONFIRMATION_ERROR';
export const RESEND_CONFIRMATION_EMAIL_FETCH = 'RESEND_CONFIRMATION_EMAIL_FETCH';
export const RESEND_CONFIRMATION_EMAIL_SUCCESS = 'RESEND_CONFIRMATION_EMAIL_SUCCESS';
export const RESEND_CONFIRMATION_EMAIL_ERROR = 'RESEND_CONFIRMATION_EMAIL_ERROR';
export const REGISTER_FETCH = 'REGISTER_FETCH';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const CONFIRM_REGISTRATION_FETCH = 'CONFIRM_REGISTRATION_FETCH';
export const CONFIRM_REGISTRATION_SUCCESS = 'CONFIRM_REGISTRATION_SUCCESS';
export const CONFIRM_REGISTRATION_ERROR = 'CONFIRM_REGISTRATION_ERROR';
export const PASSWORD_RECOVERY_FETCH = 'PASSWORD_RECOVERY_FETCH';
export const PASSWORD_RECOVERY_SUCCESS = 'PASSWORD_RECOVERY_SUCCESS';
export const PASSWORD_RECOVERY_ERROR = 'PASSWORD_RECOVERY_ERROR';
export const PASSWORD_RESET_FETCH = 'PASSWORD_RESET_FETCH';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';

// loginActions

export const LOGIN_VIEW_CHANGE = 'LOGIN_VIEW_CHANGE';

// forgotActions

export const FORGOT_VIEW_CHANGE = 'FORGOT_VIEW_CHANGE';

// registerActions

export const REGISTER_VIEW_CHANGE = 'REGISTER_VIEW_CHANGE';

// accountActions

export const ACCOUNT_UPDATE_FETCH = 'ACCOUNT_UPDATE_FETCH';
export const ACCOUNT_UPDATE_SUCCESS = 'ACCOUNT_UPDATE_SUCCESS';
export const ACCOUNT_UPDATE_ERROR = 'ACCOUNT_UPDATE_ERROR';
export const OPEN_ACCOUNT_DIALOG = 'OPEN_ACCOUNT_DIALOG';
export const CLOSE_ACCOUNT_DIALOG = 'CLOSE_ACCOUNT_DIALOG';

// dashboardActions

export const GET_SUMMARY_FETCH = 'GET_SUMMARY_FETCH';
export const GET_SUMMARY_SUCCESS = 'GET_SUMMARY_SUCCESS';
export const GET_SUMMARY_ERROR = 'GET_SUMMARY_ERROR';

// navigationActions

export const TOGGLE_MENU = 'TOGGLE_MENU';

// downlinesActions

export const GET_DOWNLINES_DATA_FETCH = 'GET_DOWNLINES_DATA_FETCH';
export const GET_DOWNLINES_DATA_SUCCESS = 'GET_DOWNLINES_DATA_SUCCESS';
export const GET_DOWNLINES_DATA_ERROR = 'GET_DOWNLINES_DATA_ERROR';